# https://github.com/delsner/python-flask-angular-starter/blob/master/docker-compose.dev.yml

version: "3.7"

services:
  # freeling-cnio:
  #   image: bsctemu/freeling-cnio:1.0.0
  #   ports:
  #     - 4000:4000
  #   networks:
  #     - demos

  # spaccc-pos-tagger-api:
  #   image: bsctemu/spaccc-pos-tagger
  #   build: ./backend/spaccc-pos-tagger
  #   container_name: spaccc-pos-tagger-api
  #   volumes:
  #       - ./backend/spaccc-pos-tagger:/app
  #   environment:
  #     - FLASK_ENV=development
  #   ports:
  #     - 5000:5000
  #   networks:
  #     - demos

  flask-translator:
    build: ./backend/translator
    container_name: flask-translator
    environment:
      - FLASK_ENV=development
    command: flask run --host 0.0.0.0
    ports:
      - 5001:5000
    volumes:
      - ./backend/translator:/app

  # translator-api:
  #   image: bsctemu/translator-api
  #   build: ./backend/translator
  #   container_name: translator-api
  #   volumes:
  #       - ./backend/translator:/usr/src/app
  #   environment:
  #     - FLASK_ENV=development
  #   ports:
  #     - 5001:5000

  # pharmaconer-tagger:
  #   # image: bsctemu/pharmaconer-tagger-api
  #   build: ./backend/pharmaconer-tagger
  #   container_name: pharmaconer-tagger-api
  #   volumes:
  #       - ./backend/pharmaconer-tagger:/usr/src/app
  #   # environment:
  #   #   - FLASK_ENV=development
  #   ports:
  #     - 5002:5000
  #   networks:
  #     - backend

  # frontend:
  #   image: bsctemu/frontend
  #   build: ./frontend
  #   container_name: frontend
  #   volumes:
  #     # - /app/node_modules
  #     - ./frontend:/app
  #   ports:
  #     - 4200:4200

  angular:
    build: ./frontend
    container_name: angular
    # https://codinglatte.com/posts/angular/using-os-environment-variables-in-angular-with-docker/
    environment:
      - REST_API_URL=http://localhost:5000
      - BROWSER_SESSION_KEY=user
    command: ng serve --host 0.0.0.0
    ports:
      - 4200:4200
    volumes:
      - ./frontend:/app
  # nginx:
  #   build: ./server
  #   hostname: nginx
  #   container_name: nginx
  #   ports:
  #     - 8080:80
