version: "3.7"
services:
  angular:
    container_name: demos_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "8080:80"
    restart: always
  # flask-pos:
  #   build: ./backend/pos
  #   container_name: demos_backend_pos
  #   environment:
  #     - FLASK_APP=pos.py
  #     - SAMPLES_DIR=./samples
  #   command: flask run --host 0.0.0.0
  #   ports:
  #     - 5000:5000
  #   restart: always
  flask-translator:
    build: ./backend/translator
    container_name: demos_backend_translator
    environment:
      - SAMPLES_DIR=./samples
    command: uwsgi app.ini
    restart: always
