version: '3.7'

services:

  # flask-pos:
  #   build: ./backend/pos
  #   container_name: flask-pos-prod
  #   environment:
  #     - FLASK_APP=pos.py
  #     - SAMPLES_DIR=./samples
  #   command: flask run --host 0.0.0.0
  #   ports:
  #     - 5000:5000

  flask-translator:
    build: ./backend/translator
    container_name: flask-translator-prod
    environment:
      - FLASK_APP=translator.py
      - SAMPLES_DIR=./samples
    command: flask run --host 0.0.0.0
    ports:
      - 5001:5000

  angular:
    container_name: angular-demos-prod
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - '8080:80'