version: "3.7"
services:
  angular:
    build: ./frontend
    container_name: demos_frontend
    # https://codinglatte.com/posts/angular/using-os-environment-variables-in-angular-with-docker/
    # environment:
    #   - POS_API_URL=http://localhost:5000
    #   - TRANSLATOR_API_URL=http://localhost:5001
    #   - PHARMACONER_API_URL=http://localhost:5002
    ports:
      - 4200:4200
    volumes:
      - ./frontend:/app
    command: ng serve --host 0.0.0.0
  # freeling-cnio:
  #   image: bsctemu/freeling-cnio:1.0.0
  flask-pos:
    build: ./backend/pos
    container_name: demos_backend_pos
    environment:
      - FLASK_ENV=development
      - SAMPLES_DIR=./samples
    ports:
      - 5000:5000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend/pos:/app
    command: flask run --host 0.0.0.0
  # flask-translator:
  #   build: ./backend/translator
  #   container_name: demos_backend_translator
  #   environment:
  #     - FLASK_ENV=development
  #     - SAMPLES_DIR=./samples
  #   ports:
  #     - 5001:5000
  #   volumes:
  #     - ./backend/translator:/app
  #   command: flask run --host 0.0.0.0

  # fastapi-ner:
  #   build: ./backend/ner_api
  #   container_name: "fastapi-ner"
  #   ports:
  #     - "8000:15400"
  #   volumes:
  #     - ./backend/ner_api:/app
  flask-ner:
    build: ./backend/ner
    container_name: demos_backend_ner
    environment:
      - FLASK_ENV=development
      - SAMPLES_DIR=./samples
    ports:
      - 5002:5000
    volumes:
      - ./backend/ner:/app
    command: flask run --host 0.0.0.0
